definitions:
  github_com_zednotdead_dinners_auth_internal_domain_models.Credential:
    properties:
      id:
        type: string
      passwordHash:
        type: string
      userID:
        type: string
    type: object
  github_com_zednotdead_dinners_auth_internal_domain_models.User:
    properties:
      avatar:
        type: string
      credentials:
        items:
          $ref: '#/definitions/github_com_zednotdead_dinners_auth_internal_domain_models.Credential'
        type: array
      email:
        type: string
      id:
        type: string
      username:
        type: string
    type: object
  handler.LoginRequest:
    properties:
      password:
        example: securepassword
        minLength: 5
        type: string
      username:
        example: username
        minLength: 5
        type: string
    required:
    - password
    - username
    type: object
  handler.RegistrationRequest:
    properties:
      email:
        example: username@example.com
        type: string
      password:
        example: securepassword
        minLength: 5
        type: string
      username:
        example: username
        minLength: 5
        type: string
    required:
    - email
    - password
    - username
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: me@zed.gay
    name: API Support
    url: http://deepdi.sh/support
  description: Authentication service for the Dinners app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Dinners Auth
  version: 0.0.1
paths:
  /:
    get:
      description: Get information about currently logged in account
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_zednotdead_dinners_auth_internal_domain_models.User'
      summary: User info
      tags:
      - accounts
    post:
      consumes:
      - application/json
      description: Register a new account
      parameters:
      - description: Registration request body
        in: body
        name: registration_request
        required: true
        schema:
          $ref: '#/definitions/handler.RegistrationRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_zednotdead_dinners_auth_internal_domain_models.User'
      summary: Register
      tags:
      - accounts
  /login:
    post:
      consumes:
      - application/json
      description: Log in to the account
      parameters:
      - description: Login request object
        in: body
        name: login_request
        required: true
        schema:
          $ref: '#/definitions/handler.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_zednotdead_dinners_auth_internal_domain_models.User'
      summary: Log in
      tags:
      - accounts
swagger: "2.0"
