definitions:
  github_com_zednotdead_dinners_auth_internal_server_domain_models.Credential:
    properties:
      id:
        type: string
      passwordHash:
        type: string
      userID:
        type: string
    type: object
  github_com_zednotdead_dinners_auth_internal_server_domain_models.User:
    properties:
      avatar:
        type: string
      credentials:
        items:
          $ref: '#/definitions/github_com_zednotdead_dinners_auth_internal_server_domain_models.Credential'
        type: array
      email:
        type: string
      id:
        type: string
      username:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: me@zed.gay
    name: API Support
    url: http://deepdi.sh/support
  description: Authentication service for the Dinners app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Dinners Auth
  version: 0.0.1
paths:
  /login:
    get:
      consumes:
      - application/json
      description: Log in to the account
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_zednotdead_dinners_auth_internal_server_domain_models.User'
      summary: Log in
      tags:
      - accounts
swagger: "2.0"
